# Generated by Django 5.0.4 on 2024-05-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_alter_wife_husband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.husband'),
        ),
    ]
