# Generated by Django 5.2.8 on 2025-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
