# Generated by Django 5.0.4 on 2024-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0002_alter_userdata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='file',
            field=models.ImageField(upload_to='userdata'),
        ),
    ]
